import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import ProjectCard from '@/components/ProjectCard'


export default function Home() {
    return (
        <>
            <Head>
                <title>PeerTask</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="bg-black text-white pb-10 px-10">
                <div className="max-w-5xl mx-auto">
                    <h1 className="text-2xl font-semibold my-10 md:ml-5">Explore Projects</h1>
                    <ProjectCard />
                    <ProjectCard />
                    <ProjectCard />

                </div>
            </section>
        </>
    )
}
