import React, { useState } from 'react'
import { useRouter } from 'next/router'
import Header from '@/components/Header'
import Preferences from '@/components/Tasks'
import Head from "next/head"


const TaskInfo = () => {
    return (
        <>
            <Head>
                <title>PeerTask</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="bg-black text-white pb-6 px-10">
                <h1 className="text-2xl font-bold my-2 md:ml-2">Project Name</h1>
                <p className="text-sm md:ml-2 mt-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore atque ea aut error aliquam, molestiae ipsum perspiciatis exercitationem quisquam! Ducimus cupiditate dolore voluptates assumenda accusantium!
                </p>
                <div className="flex py-7 h-96 w-9/12 border-2 border-slate-700 rounded-xl my-8 px-5">
                    <div className="flex flex-col justify-between">
                        <div className="flex flex-col">
                            <h3 className="text-xl font-bold md:ml-2">
                                Task Name
                            </h3>
                            <p className="text-sm text-gray-400 md:ml-2 md:mt-3">
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente ipsam necessitatibus laborum perferendis itaque molestias quidem facilis rem sed, libero ea excepturi earum nesciunt vel.
                            </p>
                            <p>
                                <span className="px-5 py-2 my-5 inline-flex text-sm leading-5 font-semibold border-2 border-slate-700 rounded-xl rounded-full text-white-800">
                                    Category
                                </span>
                            </p>
                            <button className="bg-[#0284c7] w-32 text-white inline whitespace-nowrap text-sm p-3 rounded-xl mt-5">
                                Submit Proposal
                            </button>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default TaskInfo